dist: xenial

matrix:
  include:
    -language: node_js
    node_js: "8"
    before_install:
      - cd ../front/
    install:
      - npm install
      - npm install --save cross-env
      - npm install jest
    script:
      - npm test -- --coverage
