dist: xenial

matrix:
  include:
    -language: python
    before_install:
      - cd ./back
    before_script:
        - python3 manage.py makemigrations snu_moyeo
        - python3 manage.py migrate
    install:
        - sudo pip install --upgrade pip
        - sudo pip install django
        - sudo pip install djangorestframework
        - sudo pip install coverage
        - sudo pip install requests
        - sudo pip install django-cors-headers
        - sudo pip install django-rest-auth
        - sudo pip install django-allauth
    script:
        - python3 manage.py runserver&
        - sleep 3
        - coverage run --source='.' manage.py test snu_moyeo
        - coverage report
