
language: node_js
node_js: 6.9.4
install:
        - sudo npm install
        - sudo npm install --save cross-env
        - sudo npm install jest 
script:
        - cd front/ 
        - sudo npm test -- --coverage
