dist: trusty
language: node_js
node_js: 6.9.4

before_install:
        - cd front/
        - npm config set strict-ssl false
install :
        - sudo apt-get install curl
        - sudo apt-get install -y nodejs
        - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
        - sudo apt-get install npm
        - sudo npm install
        - sudo npm install --save cross-env
        - sudo npm install jest 
        - sudo npm install -g yo generator-arc
script:
        - sudo npm test -- --coverage
