dist: xenial
matrix:
  include:
    
    -language: node_js
    node_js: 6.9.4
    install:
      - sudo npm install
      - sudo npm install --save cross-env
      - sudo npm install jest 
    script:
      - cd front/ 
      - sudo npm test -- --coverage

    
    -language: python
    before_script:
      - rm ./back/db.sqlite3
      - rm ./back/snu_moyeo/migrations
      - python3 ./back/manage.py makemigrations snu_moyeo
      - python3 ./back/manage.py migrate
        
    install:
      - sudo apt-get install python3-pip
      - sudo pip3 install django
      - sudo pip3 install djangorestframework
      - sudo pip3 install coverage
      - sudo pip3 install requests
      - sudo pip3 install django-cors-headers
      - sudo pip3 install django-rest-auth
      - sudo pip3 install django-allauth
  
    script:
      - cd back/
      - python3 manage.py runserver&
      - sleep 3
      - coverage run --source = '.' manage.py test snu_moyeo
      - coverage report

