language: generic
matrix:
        include:
                -language: node_js
                node_js: 6.9.4
                before_install: 
                      - cd ./front
                install:
                        - npm install 
                script: 
                        - npm test 
