dist: xenial

matrix:
  include:
    - language: node_js
      cache:
        directories:
          - front/node_modules
      node_js: "10"
      before_install:
        - cd front
      install:
        - npm install
        - npm install --save cross-env
        - npm install jest
        - npm install semantic-ui-react --save
        - npm install mock-local-storage --save-dev
      script:
        - npm test -- --coverage

    - language: python
      before_install:
        - cd back
      install:
        - pip install django==2.2.1
        - pip install djangorestframework==3.9.3
        - pip install coverage==4.5.3
        - pip install requests==2.21.0
        - pip install django-cors-headers==2.5.3
        - pip install django-tagging==0.4.6
        - pip install django-hitcount==1.3.0
        - pip install django-rest-auth==0.9.5
        - pip install django-allauth==0.39.1
        - pip install Pillow==6.0.0
        - pip install coolsms_python_sdk
      script:
        - python3 manage.py makemigrations snu_moyeo
        - python3 manage.py migrate
        - python3 manage.py runserver&
        - sleep 3
        - coverage run --source='.' manage.py test snu_moyeo
        - coverage report
