dist: xenial

matrix:
  include:
    - language: node_js
      node_js: "8"
      before_install:
        - cd front
      install:
        - npm install
        - npm install --save cross-env
        - npm install jest
      script:
        - npm test -- --coverage

    - language: python
      before_install:
        - cd back
      install:
        - sudo apt-get update
        - sudo apt-get -y install python-pip
        - sudo pip install --upgrade pip
        - sudo pip install django==2.2.1
        - sudo pip install djangorestframework==3.9.3
        - sudo pip install coverage==4.5.3
        - sudo pip install requests==2.21.0
        - sudo pip install django-cors-headers==2.5.3
        - sudo pip install Pillow
      script:
        - python manage.py makemigrations snu_moyeo
        - python manage.py migrate
        - python manage.py runserver&
        - sleep 3
        - coverage run --source='.' manage.py test snu_moyeo
        - coverage report
