language: generic

matrix:
  include:
    -language: node_js
    node_js: 6.9.4
    before_install:
      - cd ./frontend/
    install:
      - sudo npm install
      - sudo npm install --save cross-env
      - sudo npm install jest
    script:
      - sudo npm test -- --coverage
