dist: xenial
language: python

before_script:
        - rm db.sqlite3
        - rm -r ./snu_moyeo/migrations
        - python3 manage.py makemigrations snu_moyeo
        - python3 manage.py migrate
install:
        - pip install django
        - pip install djangorestframework
        - pip install coverage
        - pip install requests

script:
        - python3 manage.py runserver&
        - sleep 3
        - coverage run --source='.' manage.py test snu_moyeo
        - coverage report

