# Generated by Django 2.1.8 on 2019-05-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snu_moyeo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snuuser',
            name='meetings',
        ),
    ]
